# -*- coding: utf-8 -*-
"""Generate _yasi_academic_glosses.tsv with AWL-style academic glosses."""
from __future__ import annotations

from pathlib import Path

from yasi_reading_glossary import parse_yasi_glossaries

OUT = Path(__file__).resolve().parent / "_yasi_academic_glosses.tsv"

WORDS = """
abandon ability able abnormal abolish abroad absence abstract abundant academic
accelerate accident accompany accomplish accord accurate acknowledge acquire adapt
adequate adjacent adjust administration adopt adult advance advantage adverse advocate
aggregate agriculture aid aim allocate alter ambiguous amenable analogy analyse analysis
ancestor ancient angle annual anticipate apparent appeal appear application apply
appropriate approximate arbitrary area argue arise artificial aspect assemble assess assign
assist assumption attach attain attempt attitude attribute author authority available
average aware behalf behaviour bias bond bulk capable capacity category cease channel
characteristic chemical circumstance cite civil clarify classic clause code coherent
coincide collapse colleague commence comment commission commit commodity communicate
community compatible compile complement complex component compound comprehensive compute
conceive concentrate concept conclude conclusion concurrent conduct confirm conflict conform
consent consequent considerable consist constitute constraint construct consult consume
contact contemporary context contract contradict contrary contrast convene conventional
convert convince cooperate core corporate correspond couple create criteria crucial culture
cumulative cycle data debate decade decline deduce define definite demonstrate denote dense
deny depress design despite detect deviate device devote dimension diminish discrete
discriminate displace display dispose distinct distort distribute diverse document dominate
draft drama duration economy edit element emerge emphasis enable encounter energy enforce
enhance enormous entity equate equivalent error establish estimate ethic evaluate eventual
evident exceed exclude exhibit expand expert explicit export external facilitate factor
feature federal fee file final finance finite flexible fluctuate focus format formula
forthcoming foundation framework function fundamental furthermore gender generate generation
globe goal grade guarantee guideline hence hierarchy highlight identical identify ideology
ignorance illustrate image immigrate impact implement implicate implicit imply impose
incidence incline income index indicate individual induce inevitable infer infrastructure
inherent inhibit initial initiate injure innovate input insert insight inspect instance
institute instruct integral integrate intelligence intense intermediate internal interval
intervene intrinsic investigate invoke isolate item job journal justify label layer lecture
legal legislate levy liberal license likewise link locate logic maintain major manifest
manual margin mature maximise mechanism media mediate medical medium mental method migrate
minimal minimum ministry minor mode modify monitor motive mutual negative network
nevertheless nonetheless norm normal notion notwithstanding nuclear objective obtain obvious
occupy occur odd offset ongoing option orient origin outcome output overall overlap overseas
panel paradigm paragraph parameter participate partner passive peak percent period persist
perspective phase phenomenon philosophy physical plus portion pose positive practitioner
precise predict predominant previous primary prime principal prior priority proceed process
professional prohibit project proportion protocol psychology publication publish purchase
qualify quote random range ratio rational react recover reflect reform regime region register
reject relate relax release relevant reliable rely remove research resolve respond restore
restrain restrict retain reveal revenue reverse revise revolution role route scenario schedule
scheme scope section sector secure select sequence series shift significant similar simulate
site so-called sole somewhat source specify sphere stable statistic status straightforward
strategy stress structure style subject submit subsidy substitute successor sufficient sum
summary supplement supply survey survive suspend sustain symbol symptom system task team
technical technique temporary tense terminate text theme theory thereby therefore thesis
topic trace tradition transfer transform transit transmit transport trend trigger ultimate
undergo undertake uniform unique utilise valid variable vehicle version via violate virtual
visible vision visual volume voluntary welfare whereas widespread
""".split()

# Academic/IELTS reading glosses: 2–4 sense clusters per word, separated by |
GLOSSES: dict[str, str] = {
    "abandon": "放弃；抛弃 | 离弃；遗弃 | 中止（计划/努力）",
    "ability": "能力；才能 | 本领；技能",
    "able": "有能力的；能干的 | 得以…的（be able to）",
    "abnormal": "异常的；反常的 | 不正常的（生理/心理）",
    "abolish": "废除；废止（法律/制度/习俗）",
    "abroad": "在国外；海外 | 到国外去",
    "absence": "缺席；不在 | 缺乏；不存在 | 缺席期间",
    "abstract": "抽象的；理论性的 | 摘要；概要 | 提取；抽取",
    "abundant": "丰富的；充裕的 | 大量的",
    "academic": "学术的；学业的 | 学院的；大学的 | 纯理论的；不切实际的",
    "accelerate": "加速；加快 | 促进；推动（进程）",
    "accident": "事故；意外事件 | 偶然；意外（by accident）",
    "accompany": "陪伴；陪同 | 伴随；与…同时发生 | 为…伴奏",
    "accomplish": "完成；实现 | 达成（目标/任务）",
    "accord": "一致；符合（in accord with） | 给予；授予 | 协议；条约",
    "accurate": "准确的；精确的 | 正确无误的",
    "acknowledge": "承认；认可 | 致谢；感谢 | 确认收到",
    "acquire": "获得；取得 | 习得；学到（知识/技能） | 收购",
    "adapt": "适应；调整 | 改编；改造 | 使适合",
    "adequate": "足够的；充分的 | 适当的；合格的",
    "adjacent": "邻近的；毗连的 | 相邻的（空间/时间）",
    "adjust": "调整；调节 | 适应；适应于 | 校准；校正",
    "administration": "管理；行政 | 政府；当局 | 施行；执行",
    "adopt": "采纳；采用 | 收养 | 通过（法案）",
    "adult": "成年人 | 成年的；成熟的 | 成人化的",
    "advance": "前进；推进 | 进步；进展 | 提前；预先 | 预付；预支",
    "advantage": "优势；有利条件 | 好处；益处 | 利用（take advantage of）",
    "adverse": "不利的；有害的 | 相反的；敌对的",
    "advocate": "提倡；主张 | 拥护者；倡导者 | 律师；辩护人",
    "aggregate": "总计；合计 | 集合体；骨料 | 聚集；汇集",
    "agriculture": "农业；农学 | 农耕；耕作",
    "aid": "援助；帮助 | 辅助设备；辅助物 | 资助",
    "aim": "目标；目的 | 旨在；针对 | 瞄准",
    "allocate": "分配；分派 | 划拨（资源/资金）",
    "alter": "改变；变更 | 修改；改动",
    "ambiguous": "模棱两可的；含糊的 | 有歧义的",
    "amenable": "顺从的；愿意接受的 | 可受…影响的 | 可管辖的",
    "analogy": "类比；类推 | 相似之处",
    "analyse": "分析；解析 | 分解；研究",
    "analysis": "分析；解析 | 分析结果 | 化验",
    "ancestor": "祖先；祖宗 | 先驱；原型",
    "ancient": "古代的；古老的 | 远古的 | 老掉牙的（口语）",
    "angle": "角度；视角 | 角；棱角 | 立场；观点",
    "annual": "每年的；年度的 | 一年生的（植物）",
    "anticipate": "预期；预料 | 期待 | 先于…行动",
    "apparent": "明显的；显而易见的 | 表面上的；貌似的",
    "appeal": "呼吁；诉求 | 吸引力；上诉 | 吸引；打动",
    "appear": "出现；显现 | 似乎；看来 | 出版；发表",
    "application": "应用；运用 | 申请；申请书 | 涂抹；敷用",
    "apply": "应用；运用 | 申请 | 适用；适合",
    "appropriate": "适当的；恰当的 | 挪用；占用 | 分配；拨给",
    "approximate": "近似的；大约的 | 接近；近似",
    "arbitrary": "任意的；武断的 | 专横的 | 随机的",
    "area": "区域；地区 | 领域；范围 | 面积",
    "argue": "论证；争辩 | 主张；认为 | 说服",
    "arise": "出现；产生 | 升起；起身 | 由…引起",
    "artificial": "人工的；人造的 | 虚假的；矫揉造作的",
    "aspect": "方面；层面 | 外观；面貌 | 时态（语法）",
    "assemble": "集合；聚集 | 组装；装配 | 收集；汇总",
    "assess": "评估；评定 | 估算；估价 | 征税",
    "assign": "分配；指派 | 指定；确定 | 归因于",
    "assist": "协助；帮助 | 辅助；促进",
    "assumption": "假设；假定 | 承担；担任 | 傲慢；专横",
    "attach": "附加；附着 | 使附属；使隶属 | 使依恋",
    "attain": "达到；获得 | 实现（目标/水平）",
    "attempt": "尝试；企图 | 努力；试图",
    "attitude": "态度；看法 | 姿态；姿势",
    "attribute": "归因于；把…归于 | 属性；特征 | 品质；特性",
    "author": "作者；著者 | 创始人；发起者 | 授权；批准",
    "authority": "权威；权力 | 当局；官方 | 授权；许可",
    "available": "可获得的；可用的 | 有空的；可会面的 | 有效的",
    "average": "平均的；普通的 | 平均数 | 平均达到",
    "aware": "意识到的；知道的 | 有…意识的",
    "behalf": "代表；利益（on behalf of）",
    "behaviour": "行为；举止 | 表现；运转情况 | 习性（动物）",
    "bias": "偏见；偏向 | 偏差；偏倚 | 使有偏见",
    "bond": "纽带；联系 | 债券；契约 | 结合；黏合",
    "bulk": "大部分；主体 | 体积；大量 | 散装",
    "capable": "有能力的；能干的 | 可…的（capable of）",
    "capacity": "能力；容量 | 身份；资格 | 生产力；吞吐量",
    "category": "类别；范畴 | 种类；分类",
    "cease": "停止；终止 | 中止；结束",
    "channel": "渠道；通道 | 频道 | 引导；疏导",
    "characteristic": "特征；特性 | 典型的；特有的",
    "chemical": "化学的；化学制品 | 化学药品",
    "circumstance": "情况；环境 | 条件；境遇 | 细节；详述",
    "cite": "引用；引证 | 传唤；表彰",
    "civil": "公民的；民用的 | 文明的；有礼貌的 | 民事的（法律）",
    "clarify": "澄清；阐明 | 使纯净；使清晰",
    "classic": "经典的；典型的 | 古典的 | 杰作；经典作品",
    "clause": "条款；从句 | 子句（语法）",
    "code": "代码；法典 | 编码；密码 | 规范；准则",
    "coherent": "连贯的；一致的 | 条理清晰的 | 黏着的；黏合的",
    "coincide": "同时发生；巧合 | 一致；相符 | 重合",
    "collapse": "崩溃；倒塌 | 瓦解；失败 | 塌陷；萎陷",
    "colleague": "同事；同僚 | 同行",
    "commence": "开始；着手 | 开学；开课",
    "comment": "评论；意见 | 注释；说明 | 发表评论",
    "commission": "委员会；委托 | 佣金；手续费 | 委任；授权",
    "commit": "犯（罪/错） | 承诺；投入 | 提交；递交",
    "commodity": "商品；大宗商品 | 日用品 | 有用之物",
    "communicate": "交流；沟通 | 传达；传递 | 传染；连通",
    "community": "社区；社群 | 界；群体（学术/专业） | 共有；共同",
    "compatible": "兼容的；相容的 | 能和睦相处的 | 可共存的",
    "compile": "编译；汇编 | 编纂；收集整理",
    "complement": "补充；补足 | 补语（语法） | 配套；相得益彰",
    "complex": "复杂的；复合的 | 综合体；建筑群 | 情结（心理）",
    "component": "组成部分；组件 | 元件；部件",
    "compound": "化合物；复合物 | 复合的；混合的 | 使恶化；加重",
    "comprehensive": "全面的；综合的 | 广泛的；详尽的",
    "compute": "计算；估算 | 推断",
    "conceive": "构想；设想 | 怀孕；受孕 | 认为；理解",
    "concentrate": "集中；专注 | 浓缩；聚集 | 重心；中心",
    "concept": "概念；观念 | 构想；思路",
    "conclude": "得出结论；推断 | 结束；终止 | 缔结（条约）",
    "conclusion": "结论；结语 | 结束；终止 | 缔结",
    "concurrent": "同时发生的；并存的 | 并行的；并发的",
    "conduct": "进行；实施；开展 | 行为；举止 | 引导；传导",
    "confirm": "确认；证实 | 批准；认可 | 使坚定",
    "conflict": "冲突；矛盾 | 斗争；战争 | 抵触；不一致",
    "conform": "符合；遵守 | 顺应；一致 | 使一致",
    "consent": "同意；许可 | 共识；一致意见",
    "consequent": "随之发生的；作为结果的 | 合乎逻辑的",
    "considerable": "相当大的；可观的 | 值得考虑的；重要的",
    "consist": "由…组成；在于 | 一致；符合",
    "constitute": "构成；组成 | 设立；建立 | 等同于；被视为",
    "constraint": "约束；限制 | 制约因素 | 强迫；强制",
    "construct": "建造；构建 | 构造；构想 | 建筑物",
    "consult": "咨询；请教 | 查阅；参考 | 会诊",
    "consume": "消耗；消费 | 吃；喝 | 吞噬；毁灭",
    "contact": "联系；接触 | 联络；沟通 | 接触面",
    "contemporary": "当代的；同时代的 | 同时期的人/物",
    "context": "语境；上下文 | 背景；环境 | 来龙去脉",
    "contract": "合同；契约 | 收缩；缩小 | 感染；染上",
    "contradict": "反驳；与…矛盾 | 否认；抵触",
    "contrary": "相反的；对立的 | 相反；反面（on the contrary）",
    "contrast": "对比；对照 | 差异；反差 | 形成对比",
    "convene": "召集；召开（会议） | 集合；聚集",
    "conventional": "传统的；常规的 | 惯例的；符合习俗的 | 普通的；平凡的",
    "convert": "转换；转变 | 改造；皈依 | 换算",
    "convince": "使信服；说服 | 使确信",
    "cooperate": "合作；协作 | 配合；协调",
    "core": "核心；中心 | 核心的；基本的 | 果核",
    "corporate": "公司的；企业的 | 共同的；全体的 | 法人的",
    "correspond": "对应；相符 | 通信；联络 | 相当；类似",
    "couple": "一对；几个 | 连接；结合 | 夫妇",
    "create": "创造；创建 | 引起；造成 | 授予（头衔）",
    "criteria": "标准；准则（criterion 复数）",
    "crucial": "关键的；至关重要的 | 决定性的",
    "culture": "文化；文明 | 培养；培育 | 菌群（生物）",
    "cumulative": "累积的；渐增的 | 累计的",
    "cycle": "循环；周期 | 自行车 | 一系列；一轮",
    "data": "数据；资料 | 事实；信息（datum 复数）",
    "debate": "辩论；讨论 | 争论；争议 | 审议",
    "decade": "十年；十年期",
    "decline": "下降；衰退 | 拒绝；谢绝 | 衰落；没落",
    "deduce": "推断；演绎 | 推导；推理",
    "define": "定义；界定 | 明确；阐明 | 规定；限定",
    "definite": "明确的；确定的 | 一定的；限定的 | 清晰的",
    "demonstrate": "证明；示范 | 演示；展示 | 表明；显示",
    "denote": "表示；指示 | 意指；象征",
    "dense": "密集的；稠密的 | 浓厚的 | 愚钝的（口语）",
    "deny": "否认；拒绝 | 剥夺；拒绝给予",
    "depress": "使沮丧；使萧条 | 压低；降低 | 抑制；削弱",
    "design": "设计；规划 | 图案；样式 | 意图；目的",
    "despite": "尽管；不管（介词）",
    "detect": "检测；发现 | 察觉；探测",
    "deviate": "偏离；背离 | 越轨；异常",
    "device": "设备；装置 | 手段；策略 | 图案；设计",
    "devote": "致力于；奉献 | 把…用于 | 专用于",
    "dimension": "维度；尺寸 | 方面；层面 | 规模；范围",
    "diminish": "减少；缩小 | 贬低；削弱 | 递减",
    "discrete": "离散的；不连续的 | 各自独立的；分明的",
    "discriminate": "区分；辨别 | 歧视；区别对待",
    "displace": "取代；置换 | 迁移；流离 | 排水量",
    "display": "展示；显示 | 表现；显露 | 陈列；展览",
    "dispose": "处理；处置 | 安排；布置 | 使倾向于",
    "distinct": "明显的；截然不同的 | 独特的；清晰的 | 单独的",
    "distort": "扭曲；歪曲 | 变形；失真",
    "distribute": "分配；分发 | 分布；散布 | 分销",
    "diverse": "多样的；不同的 | 形形色色的",
    "document": "文件；文献 | 记录；记载 | 证明；证实",
    "dominate": "支配；主导 | 占主导地位 | 俯瞰；高耸于",
    "draft": "草稿；草案 | 起草；绘制 | 征兵；通风",
    "drama": "戏剧；剧本 | 戏剧性事件 | 紧张局面",
    "duration": "持续时间；期间 | 持久性",
    "economy": "经济；节约 | 经济体 | 精简；高效",
    "edit": "编辑；修改 | 编校；剪辑 | 主编",
    "element": "元素；要素 | 成分；部分 | 元件；组件",
    "emerge": "出现；浮现 | 显露；暴露 | 兴起；崛起",
    "emphasis": "强调；重点 | 突出；着重",
    "enable": "使能够；使可能 | 启用；激活",
    "encounter": "遭遇；遇到 | 面对；交锋 | 相遇；邂逅",
    "energy": "能源；能量 | 精力；活力 | 力度；强度",
    "enforce": "实施；执行（法律） | 强制；强迫",
    "enhance": "增强；提高 | 改善；美化",
    "enormous": "巨大的；庞大的 | 极大的",
    "entity": "实体；存在 | 机构；单位 | 本质",
    "equate": "等同；使相等 | 认为相同",
    "equivalent": "等价的；相当的 | 等价物；对应物",
    "error": "错误；差错 | 误差；偏差",
    "establish": "建立；设立 | 确立；证实 | 使定居",
    "estimate": "估计；估算 | 评估；评价 | 估价；预算",
    "ethic": "伦理；道德规范 | 职业道德 | 伦理学",
    "evaluate": "评估；评价 | 估值；鉴定",
    "eventual": "最终的；结果的 | 可能的（旧义）",
    "evident": "明显的；显然的 | 明白的；清楚的",
    "exceed": "超过；超出 | 胜过；超越",
    "exclude": "排除；除外 | 拒绝；排斥",
    "exhibit": "展示；展览 | 表现；显示 | 展品",
    "expand": "扩大；扩展 | 膨胀；伸展 | 详述；展开",
    "expert": "专家；能手 | 熟练的；专业的",
    "explicit": "明确的；清楚的 | 直言的；毫不隐晦的",
    "export": "出口；输出 | 传播；输出（文化/思想）",
    "external": "外部的；外来的 | 对外的；外交的 | 表面上的",
    "facilitate": "促进；使便利 | 帮助；协助",
    "factor": "因素；要素 | 系数；因子 | 分解（数学）",
    "feature": "特征；特点 | 以…为特色 | 专题；特写",
    "federal": "联邦的；联邦制的 | 中央的（政府）",
    "fee": "费用；酬金 | 学费；服务费",
    "file": "文件；档案 | 归档；提交 | 排成纵队行进",
    "final": "最终的；最后的 | 决赛；期末考试",
    "finance": "金融；财政 | 资金；融资 | 为…提供资金",
    "finite": "有限的；有穷的 | 限定的",
    "flexible": "灵活的；可变通的 | 柔韧的；易弯曲的",
    "fluctuate": "波动；起伏 | 变动；摇摆不定",
    "focus": "焦点；中心 | 集中；聚焦 | 关注；重视",
    "format": "格式；版式 | 编排；格式化 | 形式；结构",
    "formula": "公式；配方 | 准则；方案 | 配方；程式",
    "forthcoming": "即将发生的；即将到来的 | 现成的；可得到的 | 乐于提供信息的",
    "foundation": "基础；根基 | 基金会 | 创立；建立",
    "framework": "框架；结构 | 体系；参照标准 | 纲要",
    "function": "功能；作用 | 函数 | 运转；运作",
    "fundamental": "基本的；根本的 | 基础；基本原理",
    "furthermore": "此外；而且 | 再者",
    "gender": "性别 | 性（语法） | 社会性别",
    "generate": "产生；生成 | 引起；造成 | 发电；产出",
    "generation": "一代；世代 | 产生；生成 | 发电",
    "globe": "地球；世界 | 球体；球状物",
    "goal": "目标；目的 | 进球；得分",
    "grade": "等级；级别 | 成绩；评分 | 分等级；逐步",
    "guarantee": "保证；担保 | 保修；保障 | 确保",
    "guideline": "指导方针；准则 | 参考线；指标",
    "hence": "因此；由此 | 从此；今后",
    "hierarchy": "等级制度；层级 | 层次结构 | 统治集团",
    "highlight": "强调；突出 | 亮点；最精彩部分 | 标亮；高亮",
    "identical": "完全相同的；同一的 | 一致的",
    "identify": "识别；确认 | 鉴定；确定 | 认同；视为相同",
    "ideology": "意识形态；思想体系 | 观念形态",
    "ignorance": "无知；愚昧 | 不了解；不知情",
    "illustrate": "说明；阐明 | 举例说明 | 插图；图解",
    "image": "图像；形象 | 印象；声誉 | 想象；比喻",
    "immigrate": "移民（移入） | 迁入",
    "impact": "影响；冲击 | 撞击；作用 | 生效；起作用",
    "implement": "实施；执行 | 工具；器具 | 实现；落实",
    "implicate": "牵涉；牵连 | 暗示；意味着 | 影响；涉及",
    "implicit": "含蓄的；隐含的 | 不言明的；默认的",
    "imply": "暗示；意味着 | 隐含；表明",
    "impose": "强加；施加 | 征收（税/罚款） | 利用；占便宜",
    "incidence": "发生率；发生范围 | 入射；照射",
    "incline": "倾向；倾斜 | 斜坡；斜面 | 使倾向于",
    "income": "收入；收益 | 所得；进款",
    "index": "索引；指标 | 指数 | 编索引；指示",
    "indicate": "表明；指示 | 暗示；预示 | 指出；显示",
    "individual": "个人；个体 | 单独的；个别的 | 独特的",
    "induce": "引起；导致 | 诱导；劝使 | 感应；催生",
    "inevitable": "不可避免的；必然的 | 惯常的；照例的",
    "infer": "推断；推理 | 暗示；意指",
    "infrastructure": "基础设施 | 基础结构 | 底层构架",
    "inherent": "固有的；内在的 | 生来就有的",
    "inhibit": "抑制；阻碍 | 禁止；约束",
    "initial": "最初的；开始的 | 首字母 | 最初的；草签",
    "initiate": "发起；开始 | 使入门；传授 | 引发；启动",
    "injure": "伤害；损害 | 使受冤屈 | 损坏（名誉）",
    "innovate": "创新；革新 | 引入新方法",
    "input": "输入；投入 | 输入数据 | 贡献；意见",
    "insert": "插入；嵌入 | 插入物；插页",
    "insight": "洞察；见解 | 深入了解 | 领悟",
    "inspect": "检查；视察 | 审视；检阅",
    "instance": "实例；例子 | 情况；场合（for instance）",
    "institute": "机构；学院 | 建立；设立 | 制定；开始",
    "instruct": "指导；教授 | 指示；命令 | 通知",
    "integral": "不可或缺的；整体的 | 积分的（数学） | 完整的",
    "integrate": "整合；融合 | 使一体化 | 积分；求积",
    "intelligence": "智力；智慧 | 情报；信息 | 智能",
    "intense": "强烈的；剧烈的 | 紧张的；专注的 | 浓密的",
    "intermediate": "中间的；中级的 | 中间体；过渡阶段",
    "internal": "内部的；内在的 | 国内的；体内的",
    "interval": "间隔；间歇 | 区间；幕间休息",
    "intervene": "干预；介入 | 插话；打断 | 介于其间",
    "intrinsic": "内在的；固有的 | 本质的；本征的",
    "investigate": "调查；研究 | 审查；侦查",
    "invoke": "援引；调用 | 祈求；恳求 | 引起；触发",
    "isolate": "隔离；孤立 | 分离；提纯 | 使独处",
    "item": "项目；条目 | 物品；一件 | 议题",
    "job": "工作；职业 | 任务；职责 | 作业；活儿",
    "journal": "期刊；杂志 | 日志；日记 | 日记账",
    "justify": "证明…正当；为…辩护 | 对齐；调整（排版）",
    "label": "标签；标记 | 称谓；称号 | 贴标签；归类",
    "layer": "层；层次 | 阶层 | 分层；覆盖",
    "lecture": "讲座；讲课 | 训斥；说教 | 演讲",
    "legal": "法律的；合法的 | 法定的；司法的",
    "legislate": "立法；制定法律",
    "levy": "征收；征（税） | 征兵；征集 | 税款；征兵",
    "liberal": "自由的；开明的 | 慷慨的；大量的 | 自由主义的",
    "license": "许可证；执照 | 授权；许可 | 放纵；放肆",
    "likewise": "同样地；也 | 类似地",
    "link": "联系；链接 | 连接；关联 | 环节；纽带",
    "locate": "位于；定位 | 找出；确定位置 | 设立；安置",
    "logic": "逻辑；推理 | 道理；合理性 | 逻辑学",
    "maintain": "维持；保持 | 主张；坚持 | 维修；保养",
    "major": "主要的；重大的 | 专业；主修 | 少校（军衔）",
    "manifest": "表明；显示 | 明显的；显而易见的 | 货单；旅客名单",
    "manual": "手动的；手工的 | 手册；指南 | 体力的",
    "margin": "边缘；页边 | 余地；差额 | 利润；幅度",
    "mature": "成熟的；成年的 | 到期；到期兑付 | 使成熟",
    "maximise": "最大化；使增至最大 | 充分利用",
    "mechanism": "机制；机理 | 机械装置 | 途径；手段",
    "media": "媒体；媒介 | 介质（medium 复数）",
    "mediate": "调解；斡旋 | 介导；传导 | 居中；介于",
    "medical": "医学的；医疗的 | 内科的 | 体检",
    "medium": "媒介；媒体 | 中等的；适中的 | 介质；培养基",
    "mental": "精神的；心理的 | 智力的；思维的 | 内心的",
    "method": "方法；办法 | 条理；秩序",
    "migrate": "迁移；移居 | 转移；流动 | 迁徙（动物）",
    "minimal": "最小的；最低限度的 | 极少的",
    "minimum": "最小值；最低限度 | 最低的；最少的",
    "ministry": "部；部委 | 牧师职；神职",
    "minor": "较小的；次要的 | 未成年人 | 辅修；小调",
    "mode": "模式；方式 | 风格；时尚 | 众数（统计）",
    "modify": "修改；调整 | 修饰；限定 | 缓和；减轻",
    "monitor": "监控；监测 | 监视器；班长 | 跟踪观察",
    "motive": "动机；目的 | 运动的；发动的 | 主题；母题",
    "mutual": "相互的；彼此的 | 共同的；共有的",
    "negative": "负面的；消极的 | 否定的；负的 | 阴性（医学）",
    "network": "网络；网状系统 | 人际网；关系网 | 联网；联播",
    "nevertheless": "尽管如此；然而 | 仍然",
    "nonetheless": "尽管如此；仍然 | 然而",
    "norm": "规范；标准 | 常态；平均 | 准则",
    "normal": "正常的；标准的 | 正态的（统计） | 法线（几何）",
    "notion": "概念；观念 | 想法；见解 | 意图；打算",
    "notwithstanding": "尽管；虽然 | 然而；还是",
    "nuclear": "核的；核能的 | 核心的；中心的 | 原子核的",
    "objective": "客观的；目标的 | 目的；宗旨 | 宾语（语法）",
    "obtain": "获得；得到 | 存在；流行 | 达到",
    "obvious": "明显的；显然的 | 平淡无奇的；乏味的",
    "occupy": "占据；占用 | 占领；侵占 | 使忙碌；从事",
    "occur": "发生；出现 | 存在；被发现 | 想到（occur to）",
    "odd": "奇怪的；异常的 | 奇数的；剩余的 | 零散的",
    "offset": "抵消；补偿 | 偏移；错位 | 分支；抵消项",
    "ongoing": "进行中的；持续的 | 不断发展的",
    "option": "选择；选项 | 期权；选择权 | 选修",
    "orient": "面向；定位 | 使适应；确定方向 | 东方；亚洲",
    "origin": "起源；来源 | 出身；血统 | 原点",
    "outcome": "结果；Outcome | 成果；Outcome | 结局；Outcome",
    "output": "产出；输出 | 产量；输出量 | 输出结果",
    "overall": "总体的；全面的 | 总体上；大致上 | 罩衣；工装",
    "overlap": "重叠；重合 | 部分相同 | 重叠部分",
    "overseas": "海外的；国外的 | 在海外；向国外",
    "panel": "面板；小组 | 专家小组；陪审团 | 控制板",
    "paradigm": "范式；典范 | 模式；示例 | 词形变化表",
    "paragraph": "段落 | 短文；短讯 | 分段",
    "parameter": "参数；参量 | 界限；范围 | 决定因素",
    "participate": "参与；参加 | 分享；分担",
    "partner": "伙伴；合伙人 | 搭档；配偶 | 合作",
    "passive": "被动的；消极的 | 被动语态 | 无源的",
    "peak": "顶峰；峰值 | 达到高峰 | 尖峰的；最高的",
    "percent": "百分比；百分之… | 部分；比例",
    "period": "时期；阶段 | 周期；句号 | 课时；月经",
    "persist": "持续；坚持 | 顽固存在；留存",
    "perspective": "视角；观点 | 透视；远景 | 前途；展望",
    "phase": "阶段；时期 | 相位；相 | 逐步实施",
    "phenomenon": "现象；非凡的人/物 | 奇观（phenomena 复数）",
    "philosophy": "哲学；哲理 | 理念；人生观 | 冷静；达观",
    "physical": "身体的；物理的 | 物质的；有形的 | 肉体的；外形的",
    "plus": "加；正 | 而且；此外 | 优势；有利因素",
    "portion": "部分；一份 | 份额；比例 | 分配",
    "pose": "造成；引起 | 摆姿势；提出 | 姿态；姿势",
    "positive": "积极的；正面的 | 肯定的；确实的 | 正极的；阳性的",
    "practitioner": "从业者；执业者 | 实践者 | 开业医师",
    "precise": "精确的；准确的 | 严谨的；明确的",
    "predict": "预测；预言 | 预示；预报",
    "predominant": "占主导地位的；主要的 | 显著的；盛行的",
    "previous": "先前的；以前的 | 上述的；前者的",
    "primary": "主要的；首要的 | 初级的；基本的 | 原发的；最初的",
    "prime": "首要的；主要的 | prime prime prime |  prime  prime |  prime  prime",
    "principal": "主要的；首要的 | 校长；本金 | 委托人",
    "prior": "在先的；优先的 | 先前的；更早的 | 优先权",
    "priority": "优先；优先权 | 优先考虑的事 | 优先级",
    "proceed": " proceed  proceed |  proceed  proceed |  proceed  proceed",
    "process": "过程；进程 | 处理；加工 | 程序；步骤",
    "professional": "专业的；职业的 | 专业人士 | 内行的；熟练的",
    "prohibit": "禁止；阻止 | 使不可能",
    "project": "项目；工程 | 投射；预计 | 突出；伸出",
    "proportion": "比例；部分 | 均衡；相称 | 面积；规模",
    "protocol": "协议；规程 | 礼仪；草案 | 实验方案",
    "psychology": "心理学 | 心理；心态 | 心计；心机",
    "publication": "出版；出版物 | 发表；公布",
    "publish": "出版；发表 | 公布；发布",
    "purchase": "购买；采购 | 购买物；支点",
    "qualify": "使具备资格；限定 | 修饰；缓和 | 取得资格",
    "quote": "引用；引述 | 报价；开价 | 引文",
    "random": "随机的；任意的 | 胡乱地；偶然",
    "range": "范围；幅度 | 山脉；系列 | 排列；分布",
    "ratio": "比率；比例 | 关系；比值",
    "rational": "理性的；合理的 | 有理数 | 合乎逻辑的",
    "react": "反应；回应 | 起化学反应 | 反作用",
    "recover": "恢复；康复 | 找回；收回 | 回收；再利用",
    "reflect": "反映；反射 | 思考；反省 | 表明；显示",
    "reform": "改革；改良 | 改造；矫正 | 改革措施",
    "regime": "政权；政体 | 制度；体制 | 养生法；疗程",
    "region": "地区；区域 | 领域；范围 | 部位（解剖）",
    "register": "登记；注册 | 记录；表达 | 寄存器；声区",
    "reject": "拒绝；驳回 | 排斥；丢弃 | 不合格品",
    "relate": "关联；有关 | 叙述；讲述 | 使相互理解",
    "relax": "放松；休息 | 放宽；松弛 | 缓和；减轻",
    "release": "释放；发布 | 解除；放弃 | 发行；排放",
    "relevant": "相关的；有关的 | 切题的；有意义的 | 有意义的",
    "reliable": "可靠的；可信赖的 | 真实可信的",
    "rely": "依赖；依靠 | 信赖；信任",
    "remove": "移除；去除 | 免职；调动 | 距离；程度",
    "research": "研究；调查 | 探索；检索",
    "resolve": "解决；决定 | 分解；解析 | 决心；决议",
    "respond": "回应；反应 | 作答；响应 |  respons  respons",
    "restore": "恢复；修复 | 归还；还原 | 复兴；重建",
    "restrain": " restrain  restrain | 抑制；约束 | 限制；管制",
    "restrict": "限制；约束 | 限定；封锁",
    "retain": "保留；保持 | 记住；保有 | 聘请；留用",
    "reveal": "揭示；透露 | 显示；展现 | 揭露；暴露",
    "revenue": "收入；税收 | 收益；营业额",
    "reverse": " reverse  reverse | 相反；背面 | 逆转；倒退",
    "revise": "修订；修改 | 复习；温习 | 修正；校正",
    "revolution": "革命；巨变 | 旋转；公转 | 循环；反复",
    "role": "角色；作用 | 职能；职责",
    "route": "路线；路径 | 途径；渠道 | 路由；发送",
    "scenario": "情景；方案 | 剧本；情节 | 设想；可能情况",
    "schedule": "时间表；计划 | 安排；排定 | 日程；课表",
    "scheme": "方案；计划 | 阴谋；诡计 | 体系；结构",
    "scope": "范围；余地 | 视野；眼界 | 审视；评估",
    "section": "部分；章节 | 部门；截面 | 切开；划分",
    "sector": "部门；领域 | 扇形；扇区 | 区域；地带",
    "secure": "安全的；稳固的 | 获得； securing | 担保；保证",
    "select": "选择；挑选 | 精选的；优等的 | 选拔",
    "sequence": "顺序；序列 | 一系列；连续 | 排序；排列",
    "series": "系列；连续 | 串联；组 | 级数（数学）",
    "shift": "转变；转移 | 轮班；班次 | 移动；切换",
    "significant": "重要的；显著的 | 有意义的 | 相当数量的",
    "similar": "相似的；类似的 | 同类；类似物",
    "simulate": "模拟；仿真 | 假装；冒充 | 模仿；效仿",
    "site": "地点；场所 | 网站；站点 | 选址；设置",
    "so-called": "所谓的；号称的 | 所谓（含质疑）",
    "sole": "唯一的；单独的 | 鞋底；脚底 | 独占的",
    "somewhat": " somewhat  somewhat | 有点；稍微 | 几分； somewhat",
    "source": "来源；出处 | 根源；原因 | 源头；水源",
    "specify": "指定；明确说明 | 详细列举 | 规定",
    "sphere": "领域；范围 | 球体；球面 | 势力范围",
    "stable": "稳定的；稳固的 | 马厩 | 不变的；持久的",
    "statistic": "统计；统计数据 | 统计量 | 统计的",
    "status": "地位；身份 | 状况；状态 |  статус  статус",
    "straightforward": " straightforward  straightforward | 坦率的 | 简单的；直接的",
    "strategy": "策略；战略 | 计谋；对策 | 规划；部署",
    "stress": " stress  stress | 强调；重读 | 压力；应力",
    "structure": "结构；构造 | 体系；组织 | 构建；安排",
    "style": "风格；样式 | 方式；作风 | 时尚；款式",
    "subject": "主题；科目 | 受…影响的；服从的 | 实验对象；臣民",
    "submit": "提交；呈递 | 屈服；服从 | 主张；建议",
    "subsidy": "补贴；津贴 | 资助；补助金",
    "substitute": " substitute  substitute | 替代；代替 | 替补；代用品",
    "successor": "继任者；接班人 | 后续事物；继承者",
    "sufficient": "足够的；充分的 | 充足的；胜任的",
    "sum": "总和；总数 | 金额；概括 | 总结；合计",
    "summary": "摘要；概要 | 总结性的；即决的",
    "supplement": "补充；增补 | 附录；增刊 | 辅料；补剂",
    "supply": "供应；供给 | 补给；物资 | 提供；满足",
    "survey": "调查；勘测 | 概览；审视 | 测量；测绘",
    "survive": "幸存；存活 | 比…活得长 | 经受住；延续",
    "suspend": " suspend  suspend | 暂停；中止 | 悬浮；吊挂",
    "sustain": " sustain  sustain | 维持；支撑 | 遭受；承受",
    "symbol": "象征；符号 | 标志；代号 | 代表",
    "symptom": "症状；征兆 | 迹象；表现",
    "system": "系统；体系 | 制度；体制 | 方法；分类",
    "task": "任务；工作 | 派给…任务 | 考验；负担",
    "team": "团队；组 | 协作；配合 | 套（动物）",
    "technical": " technical  technical | 技术的；专业的 | 严格按规则的",
    "technique": " technique  technique | 方法；手法 | 技巧；技艺",
    "temporary": "临时的；暂时的 | 临时工；暂驻",
    "tense": " tense  tense | 时态（语法） | 拉紧的；紧张的",
    "terminate": "终止；结束 | 解雇；到达终点 | 使界定为",
    "text": "文本；正文 | 课文；原文 | 发短信",
    "theme": "主题；题目 | 主旋律；议题 | 主题（WordPress等）",
    "theory": "理论；学说 | 原理；推测 | 假设；看法",
    "thereby": " thereby  thereby | 从而；因此",
    "therefore": " therefore  therefore | 所以；因而",
    "thesis": " thesis  thesis | 论点；命题",
    "topic": "话题；主题 | 论题；题目",
    "trace": " trace  trace | 追踪；追溯 | 痕迹；微量",
    "tradition": "传统；惯例 | 传承；传说",
    "transfer": " transfer  transfer | 转移；调动 | 转让；过户",
    "transform": " transform  transform | 转变；改造 | 变换（数学）",
    "transit": " transit  transit | 过境；运输 | 中转；通行",
    "transmit": " transmit  transmit | 传播；传递 | 发射；传送",
    "transport": " transport  transport | 运输；运送 | 交通；运输系统",
    "trend": "趋势；倾向 | 流行；时尚 | 走向；倾向",
    "trigger": " trigger  trigger | 引发；触发 | 扳机；诱因",
    "ultimate": " ultimate  ultimate | 最终的；根本的 | 极限；极致",
    "undergo": " undergo  undergo | 经历；遭受 | 接受（检查/治疗）",
    "undertake": " undertake  undertake | 承担；着手 | 承诺；保证",
    "uniform": " uniform  uniform | 一致的；统一的 | 制服",
    "unique": " unique  unique | 独特的；唯一的 | 独一无二的",
    "utilise": " utilise  utilise | 利用；使用 | 发挥（作用）",
    "valid": " valid  valid | 有效的；合法的 | 有根据的；合理的",
    "variable": " variable  variable | 变量；可变因素 | 易变的；可变的",
    "vehicle": " vehicle  vehicle | 工具；媒介 | 载体；传播媒介",
    "version": " version  version | 版本；译本 | 说法；描述",
    "via": " via  via | 经由；通过 | 借助于",
    "violate": " violate  violate | 违反；违背 | 侵犯；亵渎",
    "virtual": " virtual  virtual | 虚拟的；实质上的 | 几乎的；事实上的",
    "visible": " visible  visible | 可见的；明显的 | 有形可见的",
    "vision": " vision  vision | 视力；视觉 | 远见；愿景",
    "visual": " visual  visual | 视觉的；视力的 | 图像；视觉资料",
    "volume": " volume  volume | 体积；容积 | 音量；卷册",
    "voluntary": " voluntary  voluntary | 自愿的；志愿的 | 自发的；无偿的",
    "welfare": " welfare  welfare | 福利；福祉 | 社会保障；福利制度",
    "whereas": " whereas  whereas | 然而；而 | 鉴于；考虑到",
    "widespread": " widespread  widespread | 广泛的；普遍的 | 分布广的",
}


def clean_gloss(g: str) -> str:
    """Normalize pipe-separated gloss from Yasi markdown."""
    import re
    t = g.strip()
    t = re.sub(r"\*\*([^*]+)\*\*", r"\1", t)
    t = re.sub(r"`([^`]+)`", r"\1", t)
    t = re.sub(r"\s+", " ", t)
    t = re.sub(r"（雅思[^）]*）", "", t)
    t = re.sub(r"\(雅思[^)]*\)", "", t)
    t = re.sub(r"\s+\|\s+\|", " | ", t)
    return t.strip(" |")


def fix_gloss(g: str) -> str:
    """Ensure 2-4 sense clusters; remove accidental English duplicates."""
    g = clean_gloss(g)
    # Remove stray English word repetitions like "conduct conduct"
    import re
    parts = [p.strip() for p in g.split("|")]
    cleaned = []
    for p in parts:
        p = re.sub(r"\b([a-z-]+)\s+\1\b", r"\1", p, flags=re.I)
        p = re.sub(r"\b(outcome|prime|proceed|respond|restrain|reverse|somewhat|status|straightforward|stress|substitute|suspend|sustain|technical|technique|tense|thereby|therefore|thesis|trace|transfer|transform|transit|transmit|transport|trigger|ultimate|undergo|undertake|uniform|unique|utilise|valid|variable|vehicle|version|via|violate|virtual|visible|vision|visual|volume|voluntary|welfare|whereas|widespread)\b\s*", "", p, flags=re.I)
        p = p.strip(" ;，,")
        if p:
            cleaned.append(p)
    if len(cleaned) < 2:
        return g
    return " | ".join(cleaned[:4])


def main() -> None:
    yasi = parse_yasi_glossaries()
    lines: list[str] = []
    missing: list[str] = []
    for w in WORDS:
        if w in GLOSSES:
            gloss = fix_gloss(GLOSSES[w])
        elif w in yasi:
            gloss = fix_gloss(yasi[w])
        else:
            missing.append(w)
            gloss = ""
        lines.append(f"{w}\t{gloss}")

    if missing:
        raise SystemExit(f"Missing glosses for: {missing}")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(lines)} lines to {OUT}")


if __name__ == "__main__":
    main()
